mysql:
  address: "127.0.0.1"
  port: "3306"
  password: "123456"
  database: "stream_hub"
  name: "root"
  conf: "charset=utf8&parseTime=true&loc=Local"

redis:
  address: "192.168.233.128"
  port: "6379"
  db: 0
  password: ""

jwt:
  refresh: 7
  access: 1

elasticsearch:
  address: "http://192.168.233.128"
  port: "9200"

secretKey: "qing"

email:
  username: "1457800511@qq.com"
  password: "mpfbwsxwakbbfgdg"
  host: "smtp.qq.com"
  port: 587

logger:
  max_size: 300
  duration: 5

consul:
  addr: "192.168.233.128"
  port: "8500"

kafka:
  addr: "192.168.233.128"
  port: "9092"

clickhouse:
  addr: "192.168.233.128"
  port: "9000"
  database: "stream_hub"
  username: "default"

minio:
  endpoint: "192.168.233.128"
  port: "9100"
  access_key: "EbYqBQqKYmkVaWKLaQ2k"
  secret_key: "fkTDYiFFU5ilcgEDz2kx4ZZjpIuCMzVPUZGkKMcC"

mongodb:
  addr: "192.168.233.128"
  port: "27017"

ratelimiter:
  window_size: 10000
  base_limit: 200
  script_path: "./script/ratelimiter/sliding_window.lua"